DEFAULT_SYSTEM_NUM = "9223173098"
DEFAULT_UNREGISTERED_MSG = "You have not been registered into the system. Please contact your hospital or project manager for registration."
DEFAULT_CLOSE_MSG = "Ye Case, Patient |PATIENT| ki liye, bund hogaya. Apko kisi karan is case ka jawab nahi mile aur abhi bhi jewab ke jerurat he tho dubara REQ ka sms kare." 
DEFAULT_REQ_FORMAT_MSG = "Sorry, wrong format. Please re-send in this way: REQ (patient good name) (patient surname) (patient age (40y, A, C, I, E, P)) (patient mobile) (patient symptoms)"
DEFAULT_NO_PATIENTS_MSG = "Sorry, you are marked as a patient into the system and this project does not allow patients to send in messages directly. Please contact your project manager to amend this issue."
DEFAULT_HLP_FORMAT_MSG = "Sorry wrong format. Please re-send in this way: HLP (patient information and complaint)"
DEFAULT_NO_POINTS_MSG = "Sorry you have 0 points left. Please contact your project manager or purchase another card to continue using the service."
